=== Chasium/Chasium/apigen/dtd/api-data.dtd
<!ELEMENT api-data (api-path,(http-request|http-response|ws-request|ws-response),main-class,classes?)>
<!ELEMENT api-path (#PCDATA)>
<!ELEMENT http-request EMPTY>
<!ELEMENT http-response EMPTY>
<!ELEMENT ws-request EMPTY>
<!ELEMENT ws-response EMPTY>
<!ELEMENT main-class (class)>
<!ELEMENT class (description,(int|float|bool|string|list|object)+)>
<!ATTLIST class class-name ID #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT int (key,description)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT float (key,description)>
<!ELEMENT bool (key,description)>
<!ELEMENT string (key,description)>
<!ELEMENT list (key,description,(int-element|float-element|bool-element|string-element|list-element|object-element))>
<!ELEMENT int-element (description)>
<!ELEMENT float-element (description)>
<!ELEMENT bool-element (description)>
<!ELEMENT string-element (description)>
<!ELEMENT list-element (description,(int-element|float-element|bool-element|string-element|list-element|object-element))>
<!ELEMENT object-element (description)>
<!ATTLIST object-element class-name IDREF #REQUIRED>
<!ELEMENT object (key, description)>
<!ATTLIST object class-name IDREF #REQUIRED>
<!ELEMENT classes (class+)>

=== Chasium/Chasium/apigen/apis/login/LoginRequest.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/user/login</api-path>
    <http-request />
    <main-class>
        <class class-name="LoginRequest">
            <description>登录请求</description>
            <string>
                <key>userName</key>
                <description>用户名</description>
            </string>
            <string>
                <key>password</key>
                <description>密码</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/login/LoginResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/user/login</api-path>
    <http-request />
    <main-class>
        <class class-name="LoginResponse">
            <description>登录响应</description>
            <int>
                <key>code</key>
                <description>响应代码: 0 - login successfully, 1 - user not found, 2 - wrong password, 3 - login already, 404 - error</description>
            </int>
            <string>
                <key>session</key>
                <description>会话ID</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/lobby/RoomCreationResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/lobby</api-path>
    <http-request />
    <main-class>
        <class class-name="RoomCreationResponse">
            <description>大厅创建房间响应</description>
            <int>
                <key>id</key>
                <description>房间编号</description>
            </int>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/script/AddCardScriptResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/script</api-path>
    <http-request />
    <main-class>
        <class class-name="AddCardScriptResponse">
            <description>插入脚本请求</description>
            <int>
                <key>code</key>
                <description>返回代码</description>
            </int>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/vila/123.xml
<!DOCTYPE api-data SYSTEM "../../dtd/api-data.dtd">
<api-data>
    <api-path>/a/b/c</api-path>
    <http-request />
    <main-class>
        <class class-name="Test">
            <description>测试用类1</description>
            <int>
                <key>a1</key>
                <description>一个int</description>
            </int>
            <list>
                <key>a2</key>
                <description>一个list</description>
                <list-element>
                    <description>一个list</description>
                    <object-element class-name="Test1">
                        <description>list的元素</description>
                    </object-element>
                </list-element>
            </list>
        </class>
    </main-class>
    <classes>
        <class class-name="Test1">
            <description>测试用类1临时类1</description>
            <bool>
                <key>aAbBcCDDe</key>
                <description>一个bool</description>
            </bool>
        </class>
    </classes>
</api-data>

=== Chasium/Chasium/apigen/apis/lobby/RoomListResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/lobby</api-path>
    <http-request />
    <main-class>
        <class class-name="RoomCreationRequest">
            <description>大厅房间列表响应</description>
            <string>
                <key>hostName</key>
                <description>主持人名</description>
            </string>
            <string>
                <key>hostSession</key>
                <description>主持人会话ID</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/logout/LogoutResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/user/logout</api-path>
    <http-request />
    <main-class>
        <class class-name="LogoutResponse">
            <description>登出响应</description>
            <int>
                <key>code</key>
                <description>响应代码: 0 - logout successfully, otherwise - error</description>
            </int>
            <string>
                <key>userName</key>
                <description>用户名</description>
            </string>
        </class>
    </main-class>
</api-data>
