=== Chasium/Chasium/apigen/dtd/api-data.dtd
<!ELEMENT api-data (api-path,(http-request|http-response|ws-request|ws-response),main-class,classes?)>
<!ELEMENT api-path (#PCDATA)>
<!ELEMENT http-request EMPTY>
<!ELEMENT http-response EMPTY>
<!ELEMENT ws-request EMPTY>
<!ELEMENT ws-response EMPTY>
<!ELEMENT main-class (class)>
<!ELEMENT class (description,(int|float|bool|string|list|object)+)>
<!ATTLIST class class-name ID #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT int (key,description)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT float (key,description)>
<!ELEMENT bool (key,description)>
<!ELEMENT string (key,description)>
<!ELEMENT list (key,description,(int-element|float-element|bool-element|string-element|list-element|object-element))>
<!ELEMENT int-element (description)>
<!ELEMENT float-element (description)>
<!ELEMENT bool-element (description)>
<!ELEMENT string-element (description)>
<!ELEMENT list-element (description,(int-element|float-element|bool-element|string-element|list-element|object-element))>
<!ELEMENT object-element (description)>
<!ATTLIST object-element class-name IDREF #REQUIRED>
<!ELEMENT object (key, description)>
<!ATTLIST object class-name IDREF #REQUIRED>
<!ELEMENT classes (class+)>

=== Chasium/Chasium/apigen/apis/script/AddCardScriptRequest.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/script</api-path>
    <http-request />
    <main-class>
        <class class-name="AddCardScriptRequest">
            <description>插入脚本请求</description>
            <string>
                <key>scriptContent</key>
                <description>用户输入的可执行脚本内容</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/card_template/CreateTemplateRequest.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/card-template/create</api-path>
    <http-request />
    <main-class>
        <class class-name="CreateTemplateRequest">
            <description>创建人物卡模板请求</description>
            <string>
                <key>session</key>
                <description>用户Session</description>
            </string>
            <string>
                <key>name</key>
                <description>人物卡模板名</description>
            </string>
            <string>
                <key>template</key>
                <description>转化为Json字符串的人物卡模板</description>
            </string>
            <list>
                <key>scripts</key>
                <description>模板中的脚本列表</description>
                <string-element>
                    <description>列表中的一个脚本</description>
                </string-element>
            </list>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/room/ExitRoomRequest.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/lobby</api-path>
    <http-request />
    <main-class>
        <class class-name="ExitRoomRequest">
            <description>離開房间请求</description>
            <string>
                <key>roomID</key>
                <description>房间号</description>
            </string>
            <string>
                <key>userSession</key>
                <description>用戶会话ID</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/logout/LogoutRequset.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/user/logout</api-path>
    <http-request />
    <main-class>
        <class class-name="LogoutRequest">
            <description>登出请求</description>
            <string>
                <key>userName</key>
                <description>用户名</description>
            </string>
            <string>
                <key>session</key>
                <description>会话ID</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/register/RegisterRequest.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/user/register</api-path>
    <http-request />
    <main-class>
        <class class-name="RegisterRequest">
            <description>注册请求</description>
            <string>
                <key>userName</key>
                <description>用户名</description>
            </string>
            <string>
                <key>password</key>
                <description>密码</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/register/RegisterResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/user/register</api-path>
    <http-request />
    <main-class>
        <class class-name="RegisterResponse">
            <description>注册响应</description>
            <int>
                <key>code</key>
                <description>响应代码</description>
            </int>
            <string>
                <key>session</key>
                <description>会话ID</description>
            </string>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/lobby/JoinRoomRequest.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/lobby</api-path>
    <http-request />
    <main-class>
        <class class-name="JoinRoomRequest">
            <description>大厅加入房间请求</description>
            <string>
                <key>username</key>
                <description>用戶名</description>
            </string>
            <string>
                <key>session</key>
                <description>会话ID</description>
            </string>
            <int>
                <key>roomID</key>
                <description>房间号</description>
            </int>
        </class>
    </main-class>
</api-data>

=== Chasium/Chasium/apigen/apis/room/ExitRoomResponse.xml
<!DOCTYPE api-data SYSTEM '../../dtd/api-data.dtd'>
<api-data>
    <api-path>/lobby</api-path>
    <http-request />
    <main-class>
        <class class-name="ExitRoomResponse">
            <description>大厅创建房间响应</description>
            <int>
                <key>code</key>
                <description>响应代码: -1: fail, 0: success</description>
            </int>
        </class>
    </main-class>
</api-data>
